apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: flipkart-app-rs  
spec: # this spec define the behaviour of the replicaset 
  replicas: 2 
  selector: 
    matchLabels:
      app: flip
  template: # it defines the pod defination 
    metadata:
      labels: 
        app: flip 
    spec: # This Spec is going define the behaviour of the Pod 
      containers: 
        - name: sample-cont 
          image: muralisocial123/flipkart-clone-app:1.0
          resources:
            requests:
              cpu: 50m
              memory: 128Mi 
            limits:
              cpu: 100m
              memory: 256Mi     
          ports: 
            - containerPort: 80    
--- 
apiVersion: v1
kind: Service
metadata:
  name: flip-svc
spec:
  selector:
    app: flip
  ports:
  - port: 81
    targetPort: 80
  type: LoadBalancer 
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flipkart-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flipkart-app-rs
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 2
