apiVersion: v1 
kind: Pod 
metadata: 
  name: flipkart-app
  namespace: murali-ns 
spec: 
  containers:
    - name: sample-cont 
      image: muralisocial123/flipkart-clone-app:1.0
      ports: 
        - containerPort: 80
      